/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package bookstore;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dell
 */
public class StudentRegister extends javax.swing.JFrame {
    
    /**
     * Creates new form StudentRegister
     */
    Connection con = null;
    Statement stat = null;
    ResultSet res = null;
    public StudentRegister() {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/BookStore", "book", "store");
            stat = con.createStatement();
            res = stat.executeQuery("Select * from BOOK.USERS");
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    public boolean checkIdNumber(String idnumber){
        PreparedStatement ps;
        ResultSet rs;
        boolean checkid = false;
        String sql = "Select * from BOOK.USERS Where IDNUMBER=?";
        try{
            ps = con.prepareStatement(sql);
            ps.setString(1, idnumber);
            rs = ps.executeQuery();
            if(rs.next()){
                checkid = true;
            }
        }
        catch(SQLException e){
            Logger.getLogger(StudentRegister.class.getName()).log(Level.SEVERE, null, e);
        }
        return checkid;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 483));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/Images/Buttons/Webp.net-resizeimage.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 172);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/Images/Buttons/registeeer.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 410, 100, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID Number :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 200, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("First Name :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 240, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Last Name :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 280, 110, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSA", "BSBA", "BSIT", "BSCE", "BSCPE", "BSN" }));
        jComboBox1.setSelectedIndex(-1);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 320, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Course :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 320, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Password :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 360, 110, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 200, 190, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 240, 190, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 280, 190, 30);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(270, 360, 190, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/Images/Buttons/canceeeeel.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 410, 87, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookstore/Images/Buttons/gradient.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        String idnumber = jTextField1.getText();
        String firstname = jTextField2.getText();
        String lastname = jTextField3.getText();
        String password = jPasswordField1.getText();
        if(idnumber.equals("")){
            JOptionPane.showMessageDialog(null, "Input ID Number");
        }
        else if(checkIdNumber(idnumber)){
            JOptionPane.showMessageDialog(null, "ID Number already exists");
        }
        else if(firstname.equals("")){
            JOptionPane.showMessageDialog(null, "Input First Name");
        }
        else if(lastname.equals("")){
            JOptionPane.showMessageDialog(null, "Input Last Name");
        }
        else if(jComboBox1.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Select Course");
        }
        else if(password.equals("")){
            JOptionPane.showMessageDialog(null, "Input Password");
        }
        else{
            String course = jComboBox1.getSelectedItem().toString();
            try{
                PreparedStatement add = con.prepareStatement("insert into BOOK.USERS values (?,?,?,?,?)");
                add.setString(1, idnumber);
                add.setString(2, firstname);
                add.setString(3, lastname);
                add.setString(4, course);
                add.setString(5, password);
                int row = add.executeUpdate();
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jPasswordField1.setText("");
                jComboBox1.setSelectedIndex(-1);
                JOptionPane.showMessageDialog(null, "Account Successfully Created");
                
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        StudentLogin student = new StudentLogin();
        student.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
